const express = require("express");
const url = require("../models/url");

const router = express.Router();

// GET / - Renders the home page with all URLs generated by the logged-in user
router.get('/',async (req,res) => {
    if(!req.user) return res.redirect("/user/login");
    
    // Fetch URLs created by the current logged-in user
    const allUrls = await url.find({createdBy: req.user._id});
    return res.render("home",{
        urls: allUrls,
    });
});

module.exports = router;