const express = require("express");
const url = require("../models/url");
const {restrictTo} = require("../middleware/auth");

const router = express.Router();

router.get("/admin/urls", restrictTo(["ADMIN"]), async (req,res) =>{
    const allUrls = await URL.find({});
    return res.render("home",{
        urls: allUrls,
    })
})

// GET / - Renders the home page with all URLs generated by the logged-in user
router.get('/', restrictTo(["NORMAL"]), async (req,res) => {
    if(!req.user) return res.redirect("/user/login");
    
    // Fetch URLs created by the current logged-in user
    const allUrls = await url.find({createdBy: req.user._id});
    return res.render("home",{
        urls: allUrls,
    });
});

module.exports = router;